/******************************************************************************
*                                                                             *
*    resource.h                             Copyright(c) 2010-2016 itow,y.    *
*                                                                             *
******************************************************************************/

/*
  Connection Viewer
  Copyright(c) 2010-2016 itow,y.

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/


#define IDI_MAIN			1

#define IDB_TAB				10
#define IDB_TOOLBAR			11

#define IDM_MAIN			20
#define IDM_CONNECTION_ITEM	21
#define IDM_LOG_ITEM		22
#define IDM_GRAPH			23
#define IDM_INTERFACE_ITEM	24
#define IDM_BLOCK_ITEM		25
#define IDM_PROPERTY_ITEM	26

#define IDA_ACCEL			30

#define IDD_ABOUT			50
#define IDD_PREF_GENERAL	51
#define IDD_PREF_GRAPH		52
#define IDD_WHOIS			53
#define IDD_COLUMNS			54
#define IDD_FILTER			55

#define CM_SAVE_LIST									100
#define CM_SAVE_CONNECTION_LIST							101
#define CM_SAVE_CONNECTION_LOG							102
#define CM_EXIT											110
#define CM_COPY_LIST									200
#define CM_LOG_CLEAR									210
#define CM_PAUSE										300
#define CM_UPDATEINTERVAL_FIRST							310
#define CM_UPDATEINTERVAL_500							(CM_UPDATEINTERVAL_FIRST+0)
#define CM_UPDATEINTERVAL_1000							(CM_UPDATEINTERVAL_FIRST+1)
#define CM_UPDATEINTERVAL_2000							(CM_UPDATEINTERVAL_FIRST+2)
#define CM_UPDATEINTERVAL_3000							(CM_UPDATEINTERVAL_FIRST+3)
#define CM_UPDATEINTERVAL_5000							(CM_UPDATEINTERVAL_FIRST+4)
#define CM_UPDATEINTERVAL_LAST							CM_UPDATEINTERVAL_5000
#define CM_CONNECTION_LIST_COLUMN_SETTINGS				380
#define CM_CONNECTION_LOG_COLUMN_SETTINGS				381
#define CM_INTERFACE_LIST_COLUMN_SETTINGS				382
#define CM_BLOCK_LIST_COLUMN_SETTINGS					383
#define CM_LISTCOLUMN_FIRST								400
#define CM_LISTCOLUMN_PROCESS_NAME						(CM_LISTCOLUMN_FIRST+0)
#define CM_LISTCOLUMN_PROCESS_PATH						(CM_LISTCOLUMN_FIRST+1)
#define CM_LISTCOLUMN_PROCESS_ID						(CM_LISTCOLUMN_FIRST+2)
#define CM_LISTCOLUMN_PROTOCOL							(CM_LISTCOLUMN_FIRST+3)
#define CM_LISTCOLUMN_LOCAL_ADDRESS						(CM_LISTCOLUMN_FIRST+4)
#define CM_LISTCOLUMN_LOCAL_PORT						(CM_LISTCOLUMN_FIRST+5)
#define CM_LISTCOLUMN_REMOTE_ADDRESS					(CM_LISTCOLUMN_FIRST+6)
#define CM_LISTCOLUMN_REMOTE_PORT						(CM_LISTCOLUMN_FIRST+7)
#define CM_LISTCOLUMN_REMOTE_HOST						(CM_LISTCOLUMN_FIRST+8)
#define CM_LISTCOLUMN_COUNTRY							(CM_LISTCOLUMN_FIRST+9)
#define CM_LISTCOLUMN_CITY								(CM_LISTCOLUMN_FIRST+10)
#define CM_LISTCOLUMN_LOCATION							(CM_LISTCOLUMN_FIRST+11)
#define CM_LISTCOLUMN_STATE								(CM_LISTCOLUMN_FIRST+12)
#define CM_LISTCOLUMN_TIME								(CM_LISTCOLUMN_FIRST+13)
#define CM_LISTCOLUMN_IN_BYTES							(CM_LISTCOLUMN_FIRST+14)
#define CM_LISTCOLUMN_OUT_BYTES							(CM_LISTCOLUMN_FIRST+15)
#define CM_LISTCOLUMN_IN_BANDWIDTH						(CM_LISTCOLUMN_FIRST+16)
#define CM_LISTCOLUMN_OUT_BANDWIDTH						(CM_LISTCOLUMN_FIRST+17)
#define CM_LISTCOLUMN_MAX_IN_BANDWIDTH					(CM_LISTCOLUMN_FIRST+18)
#define CM_LISTCOLUMN_MAX_OUT_BANDWIDTH					(CM_LISTCOLUMN_FIRST+19)
#define CM_LISTCOLUMN_LAST								CM_LISTCOLUMN_MAX_OUT_BANDWIDTH
#define CM_LOGCOLUMN_FIRST								420
#define CM_LOGCOLUMN_CREATE_TIME						(CM_LOGCOLUMN_FIRST+0)
#define CM_LOGCOLUMN_UPDATE_TIME						(CM_LOGCOLUMN_FIRST+1)
#define CM_LOGCOLUMN_PROCESS_NAME						(CM_LOGCOLUMN_FIRST+2)
#define CM_LOGCOLUMN_PROCESS_PATH						(CM_LOGCOLUMN_FIRST+3)
#define CM_LOGCOLUMN_PROCESS_ID							(CM_LOGCOLUMN_FIRST+4)
#define CM_LOGCOLUMN_PROTOCOL							(CM_LOGCOLUMN_FIRST+5)
#define CM_LOGCOLUMN_LOCAL_ADDRESS						(CM_LOGCOLUMN_FIRST+6)
#define CM_LOGCOLUMN_LOCAL_PORT							(CM_LOGCOLUMN_FIRST+7)
#define CM_LOGCOLUMN_REMOTE_ADDRESS						(CM_LOGCOLUMN_FIRST+8)
#define CM_LOGCOLUMN_REMOTE_PORT						(CM_LOGCOLUMN_FIRST+9)
#define CM_LOGCOLUMN_REMOTE_HOST						(CM_LOGCOLUMN_FIRST+10)
#define CM_LOGCOLUMN_COUNTRY							(CM_LOGCOLUMN_FIRST+11)
#define CM_LOGCOLUMN_CITY								(CM_LOGCOLUMN_FIRST+12)
#define CM_LOGCOLUMN_LOCATION							(CM_LOGCOLUMN_FIRST+13)
#define CM_LOGCOLUMN_STATE								(CM_LOGCOLUMN_FIRST+14)
#define CM_LOGCOLUMN_TIME								(CM_LOGCOLUMN_FIRST+15)
#define CM_LOGCOLUMN_IN_BYTES							(CM_LOGCOLUMN_FIRST+16)
#define CM_LOGCOLUMN_OUT_BYTES							(CM_LOGCOLUMN_FIRST+17)
#define CM_LOGCOLUMN_IN_BANDWIDTH						(CM_LOGCOLUMN_FIRST+18)
#define CM_LOGCOLUMN_OUT_BANDWIDTH						(CM_LOGCOLUMN_FIRST+19)
#define CM_LOGCOLUMN_MAX_IN_BANDWIDTH					(CM_LOGCOLUMN_FIRST+20)
#define CM_LOGCOLUMN_MAX_OUT_BANDWIDTH					(CM_LOGCOLUMN_FIRST+21)
#define CM_LOGCOLUMN_LAST								CM_LOGCOLUMN_MAX_OUT_BANDWIDTH
#define CM_INTERFACECOLUMN_FIRST						450
#define CM_INTERFACECOLUMN_INTERFACE_LUID				(CM_INTERFACECOLUMN_FIRST+0)
#define CM_INTERFACECOLUMN_INTERFACE_INDEX				(CM_INTERFACECOLUMN_FIRST+1)
#define CM_INTERFACECOLUMN_INTERFACE_GUID				(CM_INTERFACECOLUMN_FIRST+2)
#define CM_INTERFACECOLUMN_ALIAS						(CM_INTERFACECOLUMN_FIRST+3)
#define CM_INTERFACECOLUMN_DESCRIPTION					(CM_INTERFACECOLUMN_FIRST+4)
#define CM_INTERFACECOLUMN_PHYSICAL_ADDRESS				(CM_INTERFACECOLUMN_FIRST+5)
#define CM_INTERFACECOLUMN_PERMANENT_PHYSICAL_ADDRESS	(CM_INTERFACECOLUMN_FIRST+6)
#define CM_INTERFACECOLUMN_MTU							(CM_INTERFACECOLUMN_FIRST+7)
#define CM_INTERFACECOLUMN_TYPE							(CM_INTERFACECOLUMN_FIRST+8)
#define CM_INTERFACECOLUMN_TUNNEL_TYPE					(CM_INTERFACECOLUMN_FIRST+9)
#define CM_INTERFACECOLUMN_MEDIA_TYPE					(CM_INTERFACECOLUMN_FIRST+10)
#define CM_INTERFACECOLUMN_PHYSICAL_MEDIUM_TYPE			(CM_INTERFACECOLUMN_FIRST+11)
#define CM_INTERFACECOLUMN_ACCESS_TYPE					(CM_INTERFACECOLUMN_FIRST+12)
#define CM_INTERFACECOLUMN_DIRECTION_TYPE				(CM_INTERFACECOLUMN_FIRST+13)
#define CM_INTERFACECOLUMN_OPERATIONAL_STATUS			(CM_INTERFACECOLUMN_FIRST+14)
#define CM_INTERFACECOLUMN_ADMINISTRATIVE_STATUS		(CM_INTERFACECOLUMN_FIRST+15)
#define CM_INTERFACECOLUMN_MEDIA_CONNECTION_STATE		(CM_INTERFACECOLUMN_FIRST+16)
#define CM_INTERFACECOLUMN_NETWORK_GUID					(CM_INTERFACECOLUMN_FIRST+17)
#define CM_INTERFACECOLUMN_CONNECTION_TYPE				(CM_INTERFACECOLUMN_FIRST+18)
#define CM_INTERFACECOLUMN_TRANSMIT_LINK_SPEED			(CM_INTERFACECOLUMN_FIRST+19)
#define CM_INTERFACECOLUMN_RECEIVE_LINK_SPEED			(CM_INTERFACECOLUMN_FIRST+20)
#define CM_INTERFACECOLUMN_IN_OCTETS					(CM_INTERFACECOLUMN_FIRST+21)
#define CM_INTERFACECOLUMN_IN_BANDWIDTH					(CM_INTERFACECOLUMN_FIRST+22)
#define CM_INTERFACECOLUMN_MAX_IN_BANDWIDTH				(CM_INTERFACECOLUMN_FIRST+23)
#define CM_INTERFACECOLUMN_IN_UNICAST_PACKETS			(CM_INTERFACECOLUMN_FIRST+24)
#define CM_INTERFACECOLUMN_IN_NON_UNICAST_PACKETS		(CM_INTERFACECOLUMN_FIRST+25)
#define CM_INTERFACECOLUMN_IN_DISCARDED_PACKETS			(CM_INTERFACECOLUMN_FIRST+26)
#define CM_INTERFACECOLUMN_IN_ERROR_PACKETS				(CM_INTERFACECOLUMN_FIRST+27)
#define CM_INTERFACECOLUMN_IN_UNKNOWN_PROTOCOL_PACKETS	(CM_INTERFACECOLUMN_FIRST+28)
#define CM_INTERFACECOLUMN_IN_UNICAST_OCTETS			(CM_INTERFACECOLUMN_FIRST+29)
#define CM_INTERFACECOLUMN_IN_MULTICAST_OCTETS			(CM_INTERFACECOLUMN_FIRST+30)
#define CM_INTERFACECOLUMN_IN_BROADCAST_OCTETS			(CM_INTERFACECOLUMN_FIRST+31)
#define CM_INTERFACECOLUMN_OUT_OCTETS					(CM_INTERFACECOLUMN_FIRST+32)
#define CM_INTERFACECOLUMN_OUT_BANDWIDTH				(CM_INTERFACECOLUMN_FIRST+33)
#define CM_INTERFACECOLUMN_MAX_OUT_BANDWIDTH			(CM_INTERFACECOLUMN_FIRST+34)
#define CM_INTERFACECOLUMN_OUT_UNICAST_PACKETS			(CM_INTERFACECOLUMN_FIRST+35)
#define CM_INTERFACECOLUMN_OUT_NON_UNICAST_PACKETS		(CM_INTERFACECOLUMN_FIRST+36)
#define CM_INTERFACECOLUMN_OUT_DISCARDED_PACKETS		(CM_INTERFACECOLUMN_FIRST+37)
#define CM_INTERFACECOLUMN_OUT_ERROR_PACKETS			(CM_INTERFACECOLUMN_FIRST+38)
#define CM_INTERFACECOLUMN_OUT_UNICAST_OCTETS			(CM_INTERFACECOLUMN_FIRST+39)
#define CM_INTERFACECOLUMN_OUT_MULTICAST_OCTETS			(CM_INTERFACECOLUMN_FIRST+40)
#define CM_INTERFACECOLUMN_OUT_BROADCAST_OCTESTS		(CM_INTERFACECOLUMN_FIRST+41)
#define CM_INTERFACECOLUMN_LAST							CM_INTERFACECOLUMN_OUT_BROADCAST_OCTESTS
#define CM_BLOCKLIST_COLUMN_FIRST						500
#define CM_BLOCKLIST_COLUMN_STATUS						(CM_BLOCKLIST_COLUMN_FIRST+0)
#define CM_BLOCKLIST_COLUMN_REMOTE_ADDRESS				(CM_BLOCKLIST_COLUMN_FIRST+1)
#define CM_BLOCKLIST_COLUMN_REMOTE_HOST					(CM_BLOCKLIST_COLUMN_FIRST+2)
#define CM_BLOCKLIST_COLUMN_COUNTRY						(CM_BLOCKLIST_COLUMN_FIRST+3)
#define CM_BLOCKLIST_COLUMN_CITY						(CM_BLOCKLIST_COLUMN_FIRST+4)
#define CM_BLOCKLIST_COLUMN_LOCATION					(CM_BLOCKLIST_COLUMN_FIRST+5)
#define CM_BLOCKLIST_COLUMN_ADDED_TIME					(CM_BLOCKLIST_COLUMN_FIRST+6)
#define CM_BLOCKLIST_COLUMN_COMMENT						(CM_BLOCKLIST_COLUMN_FIRST+7)
#define CM_BLOCKLIST_COLUMN_LAST						CM_BLOCKLIST_COLUMN_COMMENT
#define CM_RESOLVE_ADDRESSES							600
#define CM_CONNECTIONLIST_PROTOCOL_FIRST				610
#define CM_CONNECTIONLIST_PROTOCOL_TCP_V4				(CM_CONNECTIONLIST_PROTOCOL_FIRST+0)
#define CM_CONNECTIONLIST_PROTOCOL_UDP_V4				(CM_CONNECTIONLIST_PROTOCOL_FIRST+1)
#define CM_CONNECTIONLIST_PROTOCOL_TCP_V6				(CM_CONNECTIONLIST_PROTOCOL_FIRST+2)
#define CM_CONNECTIONLIST_PROTOCOL_UDP_V6				(CM_CONNECTIONLIST_PROTOCOL_FIRST+3)
#define CM_CONNECTIONLIST_PROTOCOL_LAST					CM_CONNECTIONLIST_PROTOCOL_UDP_V6
#define CM_HIDE_UNCONNECTED								615
#define CM_PROPERTY_LIST								620
#define CM_STATUSBAR									621
#define CM_PREFERENCES									622
#define CM_ABOUT										650
#define CM_FILTER_ACTIVE								700
#define CM_FILTER_INACTIVE								701
#define CM_FILTER_ACTIVE_TOGGLE							702
#define CM_FILTER_ADD									703

#define CM_CONNECTION_ITEM_COPY_REMOTE_ADDRESS			800
#define CM_CONNECTION_ITEM_COPY_REMOTE_HOST				801
#define CM_CONNECTION_ITEM_COPY_PROCESS_PATH			802
#define CM_CONNECTION_ITEM_WHOIS						810
#define CM_CONNECTION_ITEM_DISCONNECT					811
#define CM_CONNECTION_ITEM_BLOCK						812

#define CM_LOG_ITEM_COPY_REMOTE_ADDRESS					820
#define CM_LOG_ITEM_COPY_REMOTE_HOST					821
#define CM_LOG_ITEM_COPY_PROCESS_PATH					822
#define CM_LOG_ITEM_WHOIS								830
#define CM_LOG_ITEM_BLOCK								831

#define CM_INTERFACE_ITEM_COPY_DESCRIPTION					840
#define CM_INTERFACE_ITEM_COPY_PHYSICAL_ADDRESS				841
#define CM_INTERFACE_ITEM_COPY_PERMANENT_PHYSICAL_ADDRESS	842
#define CM_INTERFACE_ITEM_COPY_INTERFACE_GUID				843

#define CM_BLOCK_ITEM_SETTINGS							870
#define CM_BLOCK_ITEM_ACTIVE							871
#define CM_BLOCK_ITEM_REMOVE							872
#define CM_BLOCK_ITEM_REMOVE_ALL						873

#define CM_PROPERTY_ITEM_COPY							900

#define CM_GRAPH_INTERFACE_ALL_HARDWARE					950
#define CM_GRAPH_INTERFACE_FIRST						5000
#define CM_GRAPH_INTERFACE_LAST							5099

#define IDC_ABOUT_WEB			1000

#define IDC_PREF_FONT_INFO				1000
#define IDC_PREF_FONT_CHOOSE			1001
#define IDC_PREF_SHOWGRID				1002
#define IDC_PREF_COLOR_TEXT				1010
#define IDC_PREF_COLOR_GRID				1011
#define IDC_PREF_COLOR_BACK1			1012
#define IDC_PREF_COLOR_BACK2			1013
#define IDC_PREF_COLOR_NEW_BACK			1014
#define IDC_PREF_COLOR_SEL_TEXT			1015
#define IDC_PREF_COLOR_SEL_BACK			1016
#define IDC_PREF_MAXLOG					1020
#define IDC_PREF_MAXLOG_SPIN			1021
#define IDC_PREF_GEOIP_DATABASE			1022
#define IDC_PREF_GEOIP_DATABASE_BROWSE	1023

#define IDC_PREF_GRAPH_COLOR_BACK				1000
#define IDC_PREF_GRAPH_COLOR_GRID				1001
#define IDC_PREF_GRAPH_COLOR_CAPTION			1002
#define IDC_PREF_GRAPH_IN_BANDWIDTH_COLOR		1010
#define IDC_PREF_GRAPH_IN_BANDWIDTH_GRAPH_TYPE	1011
#define IDC_PREF_GRAPH_IN_BANDWIDTH_SCALE		1012
#define IDC_PREF_GRAPH_IN_BANDWIDTH_SCALE_SPIN	1013
#define IDC_PREF_GRAPH_IN_BANDWIDTH_SCALE_UNIT	1014
#define IDC_PREF_GRAPH_OUT_BANDWIDTH_COLOR		1015
#define IDC_PREF_GRAPH_OUT_BANDWIDTH_GRAPH_TYPE	1016
#define IDC_PREF_GRAPH_OUT_BANDWIDTH_SCALE		1017
#define IDC_PREF_GRAPH_OUT_BANDWIDTH_SCALE_SPIN	1018
#define IDC_PREF_GRAPH_OUT_BANDWIDTH_SCALE_UNIT	1019
#define IDC_PREF_GRAPH_CONNECTIONS_COLOR		1020
#define IDC_PREF_GRAPH_CONNECTIONS_GRAPH_TYPE	1021
#define IDC_PREF_GRAPH_CONNECTIONS_SCALE		1022
#define IDC_PREF_GRAPH_CONNECTIONS_SCALE_SPIN	1023

#define IDC_WHOIS_ADDRESS		1000
#define IDC_WHOIS_SERVER		1001
#define IDC_WHOIS_QUERY			1002
#define IDC_WHOIS_RESULT		1003

#define IDC_COLUMNS_LIST		1000
#define IDC_COLUMNS_UP			1001
#define IDC_COLUMNS_DOWN		1002

#define IDC_FILTER_ADDRESS_LOW	1000
#define IDC_FILTER_ADDRESS_HIGH	1001
#define IDC_FILTER_COMMENT		1002

#define IDS_COMMAND_NAME_FIRST	0

#define IDS_CONNECTIONLIST_COLUMN_FIRST	2000
#define IDS_CONNECTIONLIST_COLUMN_PROCESS_NAME		(IDS_CONNECTIONLIST_COLUMN_FIRST+0)
#define IDS_CONNECTIONLIST_COLUMN_PROCESS_PATH		(IDS_CONNECTIONLIST_COLUMN_FIRST+1)
#define IDS_CONNECTIONLIST_COLUMN_PROCESS_ID		(IDS_CONNECTIONLIST_COLUMN_FIRST+2)
#define IDS_CONNECTIONLIST_COLUMN_PROTOCOL			(IDS_CONNECTIONLIST_COLUMN_FIRST+3)
#define IDS_CONNECTIONLIST_COLUMN_LOCAL_ADDRESS		(IDS_CONNECTIONLIST_COLUMN_FIRST+4)
#define IDS_CONNECTIONLIST_COLUMN_LOCAL_PORT		(IDS_CONNECTIONLIST_COLUMN_FIRST+5)
#define IDS_CONNECTIONLIST_COLUMN_REMOTE_ADDRESS	(IDS_CONNECTIONLIST_COLUMN_FIRST+6)
#define IDS_CONNECTIONLIST_COLUMN_REMOTE_PORT		(IDS_CONNECTIONLIST_COLUMN_FIRST+7)
#define IDS_CONNECTIONLIST_COLUMN_REMOTE_HOST		(IDS_CONNECTIONLIST_COLUMN_FIRST+8)
#define IDS_CONNECTIONLIST_COLUMN_COUNTRY			(IDS_CONNECTIONLIST_COLUMN_FIRST+9)
#define IDS_CONNECTIONLIST_COLUMN_CITY				(IDS_CONNECTIONLIST_COLUMN_FIRST+10)
#define IDS_CONNECTIONLIST_COLUMN_LOCATION			(IDS_CONNECTIONLIST_COLUMN_FIRST+11)
#define IDS_CONNECTIONLIST_COLUMN_STATE				(IDS_CONNECTIONLIST_COLUMN_FIRST+12)
#define IDS_CONNECTIONLIST_COLUMN_DURATION			(IDS_CONNECTIONLIST_COLUMN_FIRST+13)
#define IDS_CONNECTIONLIST_COLUMN_IN_BYTES			(IDS_CONNECTIONLIST_COLUMN_FIRST+14)
#define IDS_CONNECTIONLIST_COLUMN_OUT_BYTES			(IDS_CONNECTIONLIST_COLUMN_FIRST+15)
#define IDS_CONNECTIONLIST_COLUMN_IN_BANDWIDTH		(IDS_CONNECTIONLIST_COLUMN_FIRST+16)
#define IDS_CONNECTIONLIST_COLUMN_OUT_BANDWIDTH		(IDS_CONNECTIONLIST_COLUMN_FIRST+17)
#define IDS_CONNECTIONLIST_COLUMN_MAX_IN_BANDWIDTH	(IDS_CONNECTIONLIST_COLUMN_FIRST+18)
#define IDS_CONNECTIONLIST_COLUMN_MAX_OUT_BANDWIDTH	(IDS_CONNECTIONLIST_COLUMN_FIRST+19)

#define IDS_CONNECTIONLOG_COLUMN_FIRST				2020
#define IDS_CONNECTIONLOG_COLUMN_CREATE_TIME		(IDS_CONNECTIONLOG_COLUMN_FIRST+0)
#define IDS_CONNECTIONLOG_COLUMN_UPDATE_TIME		(IDS_CONNECTIONLOG_COLUMN_FIRST+1)
#define IDS_CONNECTIONLOG_COLUMN_PROCESS_NAME		(IDS_CONNECTIONLOG_COLUMN_FIRST+2)
#define IDS_CONNECTIONLOG_COLUMN_PROCESS_PATH		(IDS_CONNECTIONLOG_COLUMN_FIRST+3)
#define IDS_CONNECTIONLOG_COLUMN_PROCESS_ID			(IDS_CONNECTIONLOG_COLUMN_FIRST+4)
#define IDS_CONNECTIONLOG_COLUMN_PROTOCOL			(IDS_CONNECTIONLOG_COLUMN_FIRST+5)
#define IDS_CONNECTIONLOG_COLUMN_LOCAL_ADDRESS		(IDS_CONNECTIONLOG_COLUMN_FIRST+6)
#define IDS_CONNECTIONLOG_COLUMN_LOCAL_PORT			(IDS_CONNECTIONLOG_COLUMN_FIRST+7)
#define IDS_CONNECTIONLOG_COLUMN_REMOTE_ADDRESS		(IDS_CONNECTIONLOG_COLUMN_FIRST+8)
#define IDS_CONNECTIONLOG_COLUMN_REMOTE_PORT		(IDS_CONNECTIONLOG_COLUMN_FIRST+9)
#define IDS_CONNECTIONLOG_COLUMN_REMOTE_HOST		(IDS_CONNECTIONLOG_COLUMN_FIRST+10)
#define IDS_CONNECTIONLOG_COLUMN_COUNTRY			(IDS_CONNECTIONLOG_COLUMN_FIRST+11)
#define IDS_CONNECTIONLOG_COLUMN_CITY				(IDS_CONNECTIONLOG_COLUMN_FIRST+12)
#define IDS_CONNECTIONLOG_COLUMN_LOCATION			(IDS_CONNECTIONLOG_COLUMN_FIRST+13)
#define IDS_CONNECTIONLOG_COLUMN_STATE				(IDS_CONNECTIONLOG_COLUMN_FIRST+14)
#define IDS_CONNECTIONLOG_COLUMN_DURATION			(IDS_CONNECTIONLOG_COLUMN_FIRST+15)
#define IDS_CONNECTIONLOG_COLUMN_IN_BYTES			(IDS_CONNECTIONLOG_COLUMN_FIRST+16)
#define IDS_CONNECTIONLOG_COLUMN_OUT_BYTES			(IDS_CONNECTIONLOG_COLUMN_FIRST+17)
#define IDS_CONNECTIONLOG_COLUMN_IN_BANDWIDTH		(IDS_CONNECTIONLOG_COLUMN_FIRST+18)
#define IDS_CONNECTIONLOG_COLUMN_OUT_BANDWIDTH		(IDS_CONNECTIONLOG_COLUMN_FIRST+19)
#define IDS_CONNECTIONLOG_COLUMN_MAX_IN_BANDWIDTH	(IDS_CONNECTIONLOG_COLUMN_FIRST+20)
#define IDS_CONNECTIONLOG_COLUMN_MAX_OUT_BANDWIDTH	(IDS_CONNECTIONLOG_COLUMN_FIRST+21)

#define IDS_INTERFACELIST_COLUMN_FIRST							2050
#define IDS_INTERFACELIST_COLUMN_INTERFACE_LUID					(IDS_INTERFACELIST_COLUMN_FIRST+0)
#define IDS_INTERFACELIST_COLUMN_INTERFACE_INDEX				(IDS_INTERFACELIST_COLUMN_FIRST+1)
#define IDS_INTERFACELIST_COLUMN_INTERFACE_GUID					(IDS_INTERFACELIST_COLUMN_FIRST+2)
#define IDS_INTERFACELIST_COLUMN_ALIAS							(IDS_INTERFACELIST_COLUMN_FIRST+3)
#define IDS_INTERFACELIST_COLUMN_DESCRIPTION					(IDS_INTERFACELIST_COLUMN_FIRST+4)
#define IDS_INTERFACELIST_COLUMN_PHYSICAL_ADDRESS				(IDS_INTERFACELIST_COLUMN_FIRST+5)
#define IDS_INTERFACELIST_COLUMN_PERMANENT_PHYSICAL_ADDRESS		(IDS_INTERFACELIST_COLUMN_FIRST+6)
#define IDS_INTERFACELIST_COLUMN_MTU							(IDS_INTERFACELIST_COLUMN_FIRST+7)
#define IDS_INTERFACELIST_COLUMN_TYPE							(IDS_INTERFACELIST_COLUMN_FIRST+8)
#define IDS_INTERFACELIST_COLUMN_TUNNEL_TYPE					(IDS_INTERFACELIST_COLUMN_FIRST+9)
#define IDS_INTERFACELIST_COLUMN_MEDIA_TYPE						(IDS_INTERFACELIST_COLUMN_FIRST+10)
#define IDS_INTERFACELIST_COLUMN_PHYSICAL_MEDIUM_TYPE			(IDS_INTERFACELIST_COLUMN_FIRST+11)
#define IDS_INTERFACELIST_COLUMN_ACCESS_TYPE					(IDS_INTERFACELIST_COLUMN_FIRST+12)
#define IDS_INTERFACELIST_COLUMN_DIRECTION_TYPE					(IDS_INTERFACELIST_COLUMN_FIRST+13)
#define IDS_INTERFACELIST_COLUMN_OPERATIONAL_STATUS				(IDS_INTERFACELIST_COLUMN_FIRST+14)
#define IDS_INTERFACELIST_COLUMN_ADMINISTRATIVE_STATUS			(IDS_INTERFACELIST_COLUMN_FIRST+15)
#define IDS_INTERFACELIST_COLUMN_MEDIA_CONNECTION_STATE			(IDS_INTERFACELIST_COLUMN_FIRST+16)
#define IDS_INTERFACELIST_COLUMN_NETWORK_GUID					(IDS_INTERFACELIST_COLUMN_FIRST+17)
#define IDS_INTERFACELIST_COLUMN_CONNECTION_TYPE				(IDS_INTERFACELIST_COLUMN_FIRST+18)
#define IDS_INTERFACELIST_COLUMN_TRANSMIT_LINK_SPEED			(IDS_INTERFACELIST_COLUMN_FIRST+19)
#define IDS_INTERFACELIST_COLUMN_RECEIVE_LINK_SPEED				(IDS_INTERFACELIST_COLUMN_FIRST+20)
#define IDS_INTERFACELIST_COLUMN_IN_OCTETS						(IDS_INTERFACELIST_COLUMN_FIRST+21)
#define IDS_INTERFACELIST_COLUMN_IN_BANDWIDTH					(IDS_INTERFACELIST_COLUMN_FIRST+22)
#define IDS_INTERFACELIST_COLUMN_MAX_IN_BANDWIDTH				(IDS_INTERFACELIST_COLUMN_FIRST+23)
#define IDS_INTERFACELIST_COLUMN_IN_UNICAST_PACKETS				(IDS_INTERFACELIST_COLUMN_FIRST+24)
#define IDS_INTERFACELIST_COLUMN_IN_NON_UNICAST_PACKETS			(IDS_INTERFACELIST_COLUMN_FIRST+25)
#define IDS_INTERFACELIST_COLUMN_IN_DISCARDED_PACKETS			(IDS_INTERFACELIST_COLUMN_FIRST+26)
#define IDS_INTERFACELIST_COLUMN_IN_ERROR_PACKETS				(IDS_INTERFACELIST_COLUMN_FIRST+27)
#define IDS_INTERFACELIST_COLUMN_IN_UNKNOWN_PROTOCOL_PACKETS	(IDS_INTERFACELIST_COLUMN_FIRST+28)
#define IDS_INTERFACELIST_COLUMN_IN_UNICAST_OCTETS				(IDS_INTERFACELIST_COLUMN_FIRST+29)
#define IDS_INTERFACELIST_COLUMN_IN_MULTICAST_OCTETS			(IDS_INTERFACELIST_COLUMN_FIRST+30)
#define IDS_INTERFACELIST_COLUMN_IN_BROADCAST_OCTETS			(IDS_INTERFACELIST_COLUMN_FIRST+31)
#define IDS_INTERFACELIST_COLUMN_OUT_OCTETS						(IDS_INTERFACELIST_COLUMN_FIRST+32)
#define IDS_INTERFACELIST_COLUMN_OUT_BANDWIDTH					(IDS_INTERFACELIST_COLUMN_FIRST+33)
#define IDS_INTERFACELIST_COLUMN_MAX_OUT_BANDWIDTH				(IDS_INTERFACELIST_COLUMN_FIRST+34)
#define IDS_INTERFACELIST_COLUMN_OUT_UNICAST_PACKETS			(IDS_INTERFACELIST_COLUMN_FIRST+35)
#define IDS_INTERFACELIST_COLUMN_OUT_NON_UNICAST_PACKETS		(IDS_INTERFACELIST_COLUMN_FIRST+36)
#define IDS_INTERFACELIST_COLUMN_OUT_DISCARDED_PACKETS			(IDS_INTERFACELIST_COLUMN_FIRST+37)
#define IDS_INTERFACELIST_COLUMN_OUT_ERROR_PACKETS				(IDS_INTERFACELIST_COLUMN_FIRST+38)
#define IDS_INTERFACELIST_COLUMN_OUT_UNICAST_OCTETS				(IDS_INTERFACELIST_COLUMN_FIRST+39)
#define IDS_INTERFACELIST_COLUMN_OUT_MULTICAST_OCTETS			(IDS_INTERFACELIST_COLUMN_FIRST+40)
#define IDS_INTERFACELIST_COLUMN_OUT_BROADCAST_OCTESTS			(IDS_INTERFACELIST_COLUMN_FIRST+41)

#define IDS_BLOCKLIST_COLUMN_FIRST			2100
#define IDS_BLOCKLIST_COLUMN_STATUS			(IDS_BLOCKLIST_COLUMN_FIRST+0)
#define IDS_BLOCKLIST_COLUMN_REMOTE_ADDRESS	(IDS_BLOCKLIST_COLUMN_FIRST+1)
#define IDS_BLOCKLIST_COLUMN_REMOTE_HOST	(IDS_BLOCKLIST_COLUMN_FIRST+2)
#define IDS_BLOCKLIST_COLUMN_COUNTRY		(IDS_BLOCKLIST_COLUMN_FIRST+3)
#define IDS_BLOCKLIST_COLUMN_CITY			(IDS_BLOCKLIST_COLUMN_FIRST+4)
#define IDS_BLOCKLIST_COLUMN_LOCATION		(IDS_BLOCKLIST_COLUMN_FIRST+5)
#define IDS_BLOCKLIST_COLUMN_ADDED_TIME		(IDS_BLOCKLIST_COLUMN_FIRST+6)
#define IDS_BLOCKLIST_COLUMN_COMMENT		(IDS_BLOCKLIST_COLUMN_FIRST+7)

#define IDS_PROPERTYLIST_COLUMN_FIRST	2120
#define IDS_PROPERTYLIST_COLUMN_INDEX	(IDS_PROPERTYLIST_COLUMN_FIRST+0)
#define IDS_PROPERTYLIST_COLUMN_NAME	(IDS_PROPERTYLIST_COLUMN_FIRST+1)
#define IDS_PROPERTYLIST_COLUMN_VALUE	(IDS_PROPERTYLIST_COLUMN_FIRST+2)

#define IDS_STATUS_CONNECTIONS		2200
#define IDS_STATUS_LOG				2201
#define IDS_STATUS_INTERFACES		2202
#define IDS_STATUS_BLOCK_FILTERS	2203
#define IDS_STATUS_IN_BANDWIDTH		2210
#define IDS_STATUS_OUT_BANDWIDTH	2211
#define IDS_STATUS_IN_BYTES			2212
#define IDS_STATUS_OUT_BYTES		2213

#define IDS_GRAPH_IN_BANDWIDTH				2220
#define IDS_GRAPH_OUT_BANDWIDTH				2221
#define IDS_GRAPH_CONNECTIONS				2222
#define IDS_GRAPH_ALL_HARDWARE_INTERFACES	2230

#define IDS_TAB_FIRST				2300
#define IDS_TAB_CONNECTION_LIST		(IDS_TAB_FIRST+0)
#define IDS_TAB_CONNECTION_LOG		(IDS_TAB_FIRST+1)
#define IDS_TAB_GRAPH				(IDS_TAB_FIRST+2)
#define IDS_TAB_INTERFACE_LIST		(IDS_TAB_FIRST+3)
#define IDS_TAB_BLOCK_LIST			(IDS_TAB_FIRST+4)

#define IDS_SAVELIST_FILTERS		2400
#define IDS_GEOIP_DATABASE_FILTERS	2410

#define IDS_CAPTION_ADMINISTRATOR		2500
#define IDS_CAPTION_NOT_ADMINISTRATOR	2501

#define IDS_PREF_CAPTION			2510

#define IDS_GRAPH_TYPE_LIST			2600

#define IDS_BLOCK_STATE_ENABLED		2620
#define IDS_BLOCK_STATE_DISABLED	2621

#define IDS_DEFAULT_FIXED_FONT		2900

#define IDS_ERROR_CAPTION						3000
#define IDS_ERROR_FILE_SAVE						3001
#define IDS_ERROR_WINDOW_CREATE					3002
#define IDS_ERROR_DISCONNECT					3003
#define IDS_ERROR_DISCONNECT_TITLE				3004
#define IDS_ERROR_DISCONNECT_HEADER				3005
#define IDS_ERROR_DISCONNECT_MESSAGE			3006
#define IDS_ERROR_DISCONNECT_ACCESS_DENIED		3007
#define IDS_ERROR_LIST_COPY						3008
#define IDS_ERROR_FILTER_OPEN					3009
#define IDS_ERROR_FILTER_BEGIN					3010
#define IDS_ERROR_FILTER_ADD					3011
#define IDS_ERROR_FILTER_UPDATE					3012
#define IDS_ERROR_FILTER_ENABLE					3013
#define IDS_ERROR_FILTER_ADDRESS_HEADER			3014
#define IDS_ERROR_FILTER_ADDRESS_MESSAGE		3015
#define IDS_ERROR_FILTER_ADDRESS_TITLE			3016
#define IDS_ERROR_FILTER_ADDRESS_RANGE			3017
#define IDS_ERROR_FILTER_ADDRESS_MISMATCH		3018
#define IDS_ERROR_FILTER_ALREADY_EXISTS			3019
#define IDS_ERROR_FILTER_ALREADY_EXISTS_TITLE	3020
#define IDS_ERROR_FILTER_ACCESS_DENIED_HEADER	3021
#define IDS_ERROR_FILTER_ACCESS_DENIED			3022

#define IDS_WHOIS_ERROR_FIRST					3100
#define IDS_WHOIS_ERROR_GET_HOST				(IDS_WHOIS_ERROR_FIRST+1)
#define IDS_WHOIS_ERROR_UNSUPPORTED_PROTOCOL	(IDS_WHOIS_ERROR_FIRST+2)
#define IDS_WHOIS_ERROR_SOCKET_OPEN				(IDS_WHOIS_ERROR_FIRST+3)
#define IDS_WHOIS_ERROR_CONNECT					(IDS_WHOIS_ERROR_FIRST+4)
#define IDS_WHOIS_ERROR_SEND					(IDS_WHOIS_ERROR_FIRST+5)
